-- ---------------------------------------------------------------------------
-- 010  Mark synthetic complaints
-- ---------------------------------------------------------------------------
-- scripts/generate-synthetic-grievances.js pre-fills 90 days of realistic but
-- fabricated complaints so the Officer and Collector dashboards have history
-- to work with. They live in the same table as real complaints so the
-- dashboards query one place, and this flag is what keeps them apart:
--
--   0  a real complaint filed through the portal (the default; never touched
--      by the generator)
--   1  generated; removed by `npm run dataset:unseed` or --reset-synthetic
--
-- Deleting a synthetic complaint removes its status history through the
-- existing ON DELETE CASCADE on complaint_status_history.complaint_id.
-- ---------------------------------------------------------------------------

ALTER TABLE complaints
  ADD COLUMN is_synthetic TINYINT(1) NOT NULL DEFAULT 0
    COMMENT '1 = generated by scripts/generate-synthetic-grievances.js; 0 = real';

CREATE INDEX idx_complaints_synthetic ON complaints (is_synthetic, created_at);
